### ISSUE TITLE
Error in read the manual badge

### ISSUE THREAD

**Issue by Siddharthmishraweb** [IIITM-Jay/Property-management-System-Django-Full-Stack-#1]
**Describe the bug**
There is an error in opening the manual . 
**To Reproduce**
1. Go to 'readme.md'
2. Click on 'read the manual badge'
3. Scroll down to 'project page '

**Expected behavior**
Read the manual badge should work properly.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IIITM-Jay** [comment]
The issue is being resolved!
