### ISSUE TITLE
Search button not opening into the search bar

### ISSUE THREAD

**Issue by ghost** [IIITM-Jay/Property-management-System-Django-Full-Stack-#10]
**Describe the bug**
The search button on the landing page of the website does not open into search bar.

**To Reproduce**
1. Go to 'index.html'
2. Scroll down to the whole file and find the correct place for the corrections
3. Find the position and fix it

**Expected behavior**
On clicking the search button, it should prompt to the search-bar to search something inside the system

**Comment by ckmganesh** [comment]
Hey,
What I understand is you want that search button to expand into a search bar when clicked. Am I right?

**Comment by IIITM-Jay** [comment]
Hi, @ckmganesh Thank you for looking up into this issue. :tada: :rocket: 
you are absolutely :heavy_check_mark: , the button should expand...
firstly, May you introduce a little bit about yourself

**Comment by ckmganesh** [comment]
I'm Ganesh .I try to work on issues and stuff. Can I try doing this feature?

**Comment by IIITM-Jay** [comment]
Of course Ganesh! @ckmganesh ... :+1: 
You can go through this and can try fixing it :sparkles: :star2: 
and let us discuss if you are facing any problems if so occur :raised_hands:

**Comment by ckmganesh** [comment]
Thanks
Do you mind if I change the code

**Comment by IIITM-Jay** [comment]
Yes @ckmganesh you can do that but first you have to fork the repository and then you can able to proceed further and can do a PR.

**Comment by ckmganesh** [comment]
Yeah sure
I'll try this feature and will let you know soon

**Comment by Rohit-bisht-rise** [comment]
@IIITM-Jay Hello Jay, myself Rohit Bisht, as a participator of DWoC, want to know is this issue still open, if yes please assign it to me

**Comment by IIITM-Jay** [comment]
Rohit @Rohit-bisht-rise can you introduce a little bit of yourself...

**Comment by ckmganesh** [comment]
@IIITM-Jay Hey there,I had my university exams throughout the week. I can start where I left from tomorrow. I'm sorry for the delay. Is that okay?

**Comment by Rohit-bisht-rise** [comment]
@ckmganesh you continue to work on this, I thought you are not doing it......

**Comment by IIITM-Jay** [comment]
@Rohit-bisht-rise Rohit you can work on any other issue of your wish ... Then discuss your view points there at the new issue..

**Comment by IIITM-Jay** [comment]
> @IIITM-Jay Hey there,I had my university exams throughout the week. I can start where I left from tomorrow. I'm sorry for the delay. Is that okay?

Have your University exams over.... Then you can start working

**Comment by IIITM-Jay** [comment]
Rohit @Rohit-bisht-rise you haven't talked about your institute, year and branch of study...
This is one of the general way to introduce yourself into a community.. and I should know my contributing members

**Comment by Rohit-bisht-rise** [comment]
Hello @IIITM-Jay, 
myself Rohit Bisht, 2-year student of BCA in Maharaja Surajmal Institute ( IP University).
Right Now examinations are going..., hope to get free as possible and contribute and learn with you all.
Thanks
