### ISSUE TITLE
Image caption to be added

### ISSUE THREAD

**Issue by IIITM-Jay** [IIITM-Jay/Property-management-System-Django-Full-Stack-#14]
**Describe the bug**
The caption is not added to the road map image in the ***README.md*** file. It's needed so as to get to know about what can we get through this image/ figure.

**To Reproduce**
1. Go to 'README.md'
2. Find the image location in the file
3. Add the caption to the image
4. Provide the screenshot
5. Do the  PR and get merged and become the first-time contributor :tada: :sparkles: :rocket: 

**Expected behavior**
A clear and concise caption for the road map image embedded in the ***README*** file

**Comment by 96RadhikaJadhav** [comment]
@IIITM-Jay  Could you please assign this issue to me? I wish to work on it.

**Comment by Amit366** [comment]
Sir I would like to solve this.

**Comment by IIITM-Jay** [comment]
@Amit366 Amit may I know little bit of yours, like in which college you are studying, which year and branch... 🤗 So that I should know about my contributing members

**Comment by Amit366** [comment]
Currently I am pursuing my BTech (2nd year) in CSE from IIIT Bhubaneswar.

**Comment by IIITM-Jay** [comment]
Yeah sure you can proceed with this issue 🍾 👍

**Comment by Amit366** [comment]
Sir I have a doubt .
what type of caption should I add and also what screenshot should I provide??

**Comment by IIITM-Jay** [comment]
@Amit366 Amit you can suggest the caption as per your understanding and then we will finalize any one of them. Regarding the screenshot, you are suppose to attach the updated version with caption.

**Comment by Amit366** [comment]
![Screenshot (65)](https://user-images.githubusercontent.com/60662775/105459298-04d50180-5cb0-11eb-8f36-8a571a7c1ebc.png)

**Comment by Pranjal-2001** [comment]
Could you please assign it to me?

**Comment by Amit366** [comment]
@IIITM-Jay can I send the PR??

**Comment by IIITM-Jay** [comment]
@Amit366 yeah sure ....

**Comment by IIITM-Jay** [comment]
@Pranjal-2001 can you take another one...

**Comment by Amit366** [comment]
@IIITM-Jay sir it was marked as level 2 but now it is showing level 1.

**Comment by Amit366** [comment]
@IIITM-Jay I have sent the PR.

**Comment by IIITM-Jay** [comment]
closing this as already resolved...
