### ISSUE TITLE
Image path is not correctly embedded

### ISSUE THREAD

**Issue by Nandini-Jha** [IIITM-Jay/Property-management-System-Django-Full-Stack-#15]
**Describe the bug**
This bug is basically have a minor issue of not going to the correct path.

**To Reproduce**
1. Go to 'DBMS module'
2. Click on 'UML_class_diag.md'
3. Scroll down to the whole page and go to the location of the image tag
4. See error and fix it

**Expected behavior**
The path should be correctly written to upload it at its right place and correct dimensions.

**Comment by IIITM-Jay** [comment]
Thank you so much Nandini @Nandini-Jha , it's really a nice catch :1st_place_medal:  :tada: :champagne: 
Go ahead if you feel free to fix it and be a contributor in an open source :open_hands:

**Comment by Antsthebul** [comment]
I can help

**Comment by IIITM-Jay** [comment]
Yes @Antsthebul of course!!

**Comment by 96RadhikaJadhav** [comment]
@IIITM-Jay  Can I also work on it?

**Comment by IIITM-Jay** [comment]
@96RadhikaJadhav at current stage I will suggest you to, be stick to only issue at a time so that you can successfully resolved it and can get your PR merged. :rocket: :1st_place_medal:
