### ISSUE TITLE
Table to be kept in Center of the file

### ISSUE THREAD

**Issue by IIITM-Jay** [IIITM-Jay/Property-management-System-Django-Full-Stack-#23]
**Describe the bug**
The table providing the description of the ***Test build*** and ***status*** in the ***README.md*** file must be positioned to the center of the viewing page.

**To Reproduce**
1. Go to README.md file
2. Navigate to the table code inserted into the file.
3. Do carefully look out the code and location to make necessary changes 
4. See error and try to fix it

**Expected behavior**
The tabular must be located at the middle of the page.

**Comment by 96RadhikaJadhav** [comment]
@IIITM-Jay  Could you please assign this issue to me? I wish to work on it.

**Comment by IIITM-Jay** [comment]
@96RadhikaJadhav I think have speak to you in #11 .

**Comment by sakshikhachane** [comment]
@IIITM-Jay I would like to work on this issue.

**Comment by IIITM-Jay** [comment]
Is anyone working on this...

**Comment by 96RadhikaJadhav** [comment]
@IIITM-Jay  I would like to work on this one. Will create a PR.

**Comment by Amit366** [comment]
@IIITM-Jay can I work on this issue??

**Comment by himanshu007-creator** [comment]
> Is anyone working on this...

i am

**Comment by himanshu007-creator** [comment]
Job done . Please check https://github.com/IIITM-Jay/Property-management-System-Django-Full-Stack-/pull/36

**Comment by jatinjain001** [comment]
I would like to work on it please assign it to me
