### ISSUE TITLE
CODE OF CONDUCT FILE 

### ISSUE THREAD

**Issue by akrish4** [IIITM-Jay/Property-management-System-Django-Full-Stack-#27]
Hi @iiitmjay 

There is no code of conduct file in this repository
code of conduct is a file that will be required to a open source project for the contributors to follow the decorum
Kindly let me know if you can assign me this issue

**Comment by IIITM-Jay** [comment]
@akrish4 Hi Ananth Krishna,!
Welcome to the property management system! :houses: 
Actually this is the best idea I should say, but the thing is I am thinking to create this file after having a sort of discussion with the collaborator i.e., Nandini Jha @Nandini-Jha .
After having saying this, I would love to hear your ideas that must be included.

**Comment by akrish4** [comment]
I would say that we should include  these ponts 
- our responsibilities 
- standards that should be followed 
- the scope of this code of conduct 

Kindly pls do add the `DWOC` label 
@IIITM-Jay

**Comment by IIITM-Jay** [comment]
@akrish4  I think this file can't be included in DWOC label... because it's somewhat administrative level as I have to discuss this with the collaborators

**Comment by akrish4** [comment]
okay fine @IIITM-Jay
