### ISSUE TITLE
CONTRIBUTING FILE 

### ISSUE THREAD

**Issue by akrish4** [IIITM-Jay/Property-management-System-Django-Full-Stack-#28]
Hi @iiitmjay 
I would like to contribute to this amazing project
I would like to add a CONTRIBUTING.mdfile which will contain all contributing guidelines and all git workflow so that all newbies or beginers and even experts can look into into it and also the contributors will understand the workflow

Kindly do assign me

Kindly add the labels also

**Comment by IIITM-Jay** [comment]
Hi Anantha @akrish4 yeah sure you can work on this.... :champagne: :congratulations:

**Comment by akrish4** [comment]
Kindly pls do add the `DWOC` label instead of `DWoC` label 
@IIITM-Jay
