### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [IIITM-Jay/Property-management-System-Django-Full-Stack-#29]
Like this
![image](https://user-images.githubusercontent.com/68433936/104810293-81339480-5819-11eb-884a-f4143c3cd0f7.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by IIITM-Jay** [comment]
Hi Samir @samir-0711 can you introduce a little of yours so that I should know about my contributors and can even mention them in other projects and assign them.

Once again Welcome to the Property Management System :houses:

**Comment by samir-0711** [comment]
I am Samir Prajapati. Currently in 3rd year and pursuing B.Tech. in Computer Science and Engineering at Indian Institute of Information Technology Vadodara.

**Comment by IIITM-Jay** [comment]
@samir-0711  Samir I have assigned this to you and now you are ready to go ahead... :smile: :champagne: :1st_place_medal:
