### ISSUE TITLE
Creation of PR template

### ISSUE THREAD

**Issue by Sloth-Panda** [IIITM-Jay/Property-management-System-Django-Full-Stack-#32]
A PR template will explain the set of checklists that the pr verifies and also in addition will describe the pr too

**Comment by IIITM-Jay** [comment]
Hi @Sloth-Panda can you introduce a little bit of yourself so that I should know about my contributing members... 👍

**Comment by Sloth-Panda** [comment]
Hey, I am achyut kumar panda a sophomore from nit rourkela

**Comment by IIITM-Jay** [comment]
Achyut @Sloth-Panda can you outline your plans here regarding this issue that you have opened like what you are going to do, what will be your approach so that I can tag it accordingly

**Comment by IIITM-Jay** [comment]
@Sloth-Panda achyut are you going to work on this at shall I close it

**Comment by Sloth-Panda** [comment]
@IIITM-Jay I have already made it I can make a pr if you want?

**Comment by IIITM-Jay** [comment]
@Sloth-Panda Achyut can you give some of the outlines of how you are doing this ... How you are going to design the template... The significance etc. Using screenshot to explain is a much better way I guess

**Comment by Sloth-Panda** [comment]
![Screenshot (95)](https://user-images.githubusercontent.com/70213384/105695053-9d28eb80-5f27-11eb-927a-289c41e2312d.png)


something like this it will explain the purpose of pr fully

**Comment by IIITM-Jay** [comment]
@Sloth-Panda Achyut some points like platforms used and the wordings I must guess should be improved like try to use more of the third parties instead of the first person as this is also an art of writing the documentation 🤗

**Comment by Sloth-Panda** [comment]
@IIITM-Jay  can you elaborate a little better what you want ?

**Comment by IIITM-Jay** [comment]
closing this as not needed for the time being...
