### ISSUE TITLE
Automatic embedment and updation of Contributors table

### ISSUE THREAD

**Issue by Swastik1710** [IIITM-Jay/Property-management-System-Django-Full-Stack-#37]
As of now the Contributors table on the readme.md file is not up to date . Also one needs to update it manually each and every time. I wanna automate this task by adding a contributors table which will update automatically. 
Moreover, I wanna add a separate line to showcase the project admin if you want.

**Comment by Swastik1710** [comment]
Hey @IIITM-Jay ,
I'm Swastik , a 2nd year Information Science undergrad and an Open Source enthusiast.
Looking forward to working with you.

**Comment by IIITM-Jay** [comment]
@Swastik1710 swastik once again welcoming you to work on this repo...🤗
May I know from which college you are..
BTW, your idea is absolutely no doubt commendable and I would love to see forward to it.
May I know the outlines, the format, the languages you are going to incorporate and the final outcome how it's going to be looked...

**Comment by Swastik1710** [comment]
Thank you so much @IIITM-Jay 
I'm from CMRIT Bangalore 
I'll be adding a dynamic link to the readme file which extracts the images of all the contributors of the required repo and puts it together.
I'll be sharing a screenshot for the same asap.
Btw , loved your enthusiasm towards the project.
I'm more than happy to be able to contribute to this Project.

**Comment by Swastik1710** [comment]
Here's how it'll look. Do let me know your views so that I can go ahead with a PR.

![Readme](https://user-images.githubusercontent.com/71871571/106352587-60376d00-630a-11eb-8f1d-61cc63f3b393.jpg)

**Comment by IIITM-Jay** [comment]
> Thank you so much @IIITM-Jay
> I'm from CMRIT Bangalore
> I'll be adding a dynamic link to the readme file which extracts the images of all the contributors of the required repo and puts it together.
> I'll be sharing a screenshot for the same asap.
> Btw , loved your enthusiasm towards the project.
> I'm more than happy to be able to contribute to this Project.

From which year you are swastik @Swastik1710

**Comment by IIITM-Jay** [comment]
Yeah sure go ahead with the pr and then we will discuss the necessary enhancement there

**Comment by Swastik1710** [comment]
> > Thank you so much @IIITM-Jay
> > I'm from CMRIT Bangalore
> > I'll be adding a dynamic link to the readme file which extracts the images of all the contributors of the required repo and puts it together.
> > I'll be sharing a screenshot for the same asap.
> > Btw , loved your enthusiasm towards the project.
> > I'm more than happy to be able to contribute to this Project.
> 
> From which year you are swastik @Swastik1710

As mentioned in a previous message I'm a 2nd Year Information Science undergrad ✌🏻

**Comment by Swastik1710** [comment]
Hey @IIITM-Jay , sorry for the delay.
I got stuck with some college exam stuff.

**Comment by Swastik1710** [comment]
So for what you're asking, we need to install a bot named AllContributors bot.
And then you only need to comment a line on the Pull Requests like this:
" @all-contributors please add @xxx for bug "and it will make a PR regarding the same, and once you accept the PR , the following Contributor will get added automatically to the table in the same format as you said you want.

**Comment by IIITM-Jay** [comment]
> So for what you're asking, we need to install a bot named AllContributors bot.
> And then you only need to comment a line on the Pull Requests like this:
> " @all-contributors please add @xxx for bug "and it will make a PR regarding the same, and once you accept the PR , the following Contributor will get added automatically to the table in the same format as you said you want.
> Or else even the contributors themselves can write the above command and the bot will create a PR for the same, and after you merge it, the contributor will get added to the table.

@Swastik1710 exactly swastik what I want to say....
So are you going ahead with that?

**Comment by Swastik1710** [comment]
Yeah @IIITM-Jay 
You'll have to add the bot to your github repo as only the owner can do so. 
I'll make a PR with the changes:
Added a new line which showcases the project admin.
And then you can use the command to add me as a Contributor to check whether it's working or not.

**Comment by Swastik1710** [comment]
Hey @IIITM-Jay,
Thanks for accepting it. 
But it's a bit disappointing seeing a level 5 issue change to level 1.
Even after doing exactly what you've asked for.
